In [1]:
# Ljung-Box test

import numpy as np
import pandas as pd
import statsmodels.api as sm



In [5]:
# create rando mtime series data

data = [132,146,129,144,141,139,131,133,148,136,132,146,129,144,141,139,131,133,148,136]

In [22]:
# oto correlation
acf = sm.tsa.acf(data, nlags=5,qstat=True)
pacf = sm.tsa.pacf(data, nlags=5, method='ldb')
acf, pacf

((array([ 1.        , -0.46605335, -0.10770561,  0.02490738,  0.00279081,
          0.13688565]),
  array([5.03002724, 5.31359496, 5.3296518 , 5.32986599, 5.87950464]),
  array([0.02491151, 0.07017259, 0.14918986, 0.25509406, 0.3181208 ])),
 array([ 1.        , -0.46605335, -0.41506605, -0.36973944, -0.39374976,
        -0.20179169]))

In [23]:
oto_corr = {
    'lag': np.arange(1, 6),
    'acf': np.round(acf[0][1:], 2),
    'pacf': np.round(pacf[1:], 2),
    'q': np.round(acf[1], 2),
    'p-value': np.round(acf[2], 2)
}
df = pd.DataFrame(oto_corr)

In [26]:
df

lag   acf  pacf     q  p-value
0    1 -0.47 -0.47  5.03     0.02
1    2 -0.11 -0.42  5.31     0.07
2    3  0.02 -0.37  5.33     0.15
3    4  0.00 -0.39  5.33     0.26
4    5  0.14 -0.20  5.88     0.32